version: '3.7'

services:
    web:
        build: .
        command: gunicorn core.wsgi -b 0.0.0.0:8000 --log-level DEBUG
        env_file:
            - .env
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres:11
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:

